### ISSUE TITLE
[Feature Request] Force spawn on join

### ISSUE THREAD

**Issue by Folas1337** [reflexLabs/RandomSpawn#1]
I'd love to use this on my lobby where I'll be having different worlds and people spawn in random ones but I can't really do this with this plugin as I can't force spawn them when they join, so I thought I'd request that feature exactly.

So just a config setting that says forceSpawnOnJoin or something and when I set it to true, people will always be sent to one of the many random spawns when they join.

A permission to bypass it would perhaps also be cool, just in case, although I personally don't need it.

**Comment by reflexLabs** [comment]
Added (:
